//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.AspNetCore.Identity.UI.UIFrameworkAttribute("Bootstrap5")]
[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("aspnet-RetroVideoGameStore-b330d60d-ae46-44cf-8378-2ec556e5db1f")]
[assembly: System.Reflection.AssemblyCompanyAttribute("RetroVideoGameStore")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+c7fd821f1ac3628d1a6afe9daf2697b83dda275f")]
[assembly: System.Reflection.AssemblyProductAttribute("RetroVideoGameStore")]
[assembly: System.Reflection.AssemblyTitleAttribute("RetroVideoGameStore")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

